### ISSUE TITLE
Image reading

### ISSUE THREAD

**Issue by lucianobonzatto** [piradata/wpg#3]
How can I include a camera in the model?

**Comment by piradata** [comment]
Hello, this is explained on the readme:

![image](https://github.com/piradata/wpg/assets/16529503/ea667b56-ebf9-462b-b7a6-9c35f86695be)

Look there:

https://github.com/piradata/PX4-Autopilot

And you will find the following submodule in `.gitmodules`.

https://github.dev/piradata/sitl_gazebo

There, are the drones models

![image](https://github.com/piradata/wpg/assets/16529503/5dd5876d-ca7f-4086-a4a7-170757c5ff2e)

This one for example has a cam. you can so just modify the iris model to add the cam, or change the model that is being used.

To change the model being used, instead of running the simulation with `make px4_sitl_default gazebo_iris` just use `make px4_sitl_default gazebo_iris_fpv_cam` or something like `make px4_sitl_default gazebo_typhoon_h480` as said in the readme note.

**Comment by piradata** [comment]
btw, fell free to submit a PR on the readme if you think it is not clear and have a better idea on how to explain this :)

**Comment by lucianobonzatto** [comment]
This command returns an error for me, so I couldn't use this template. 
I have chosen to include this fpv camera in the standard template. I am now trying to find the topic in which images are published.

**Comment by piradata** [comment]
Strange, I didnt get any errors here with that command... What error did u get?

Anyway, if you are using the same plugin for the camera as the one ive shown above, the image topic should be in the `imageTopicName` field of the xlm. Give a look below for more info:

https://docs.ros.org/en/diamondback/api/gazebo_plugins/html/group__GazeboRosCamera.html

**Comment by lucianobonzatto** [comment]
returns that the gazebo_iris_fpv_cam command does not exist
![Screenshot from 2023-07-02 11-07-28](https://github.com/piradata/wpg/assets/37905647/b0ab5867-73b1-4419-9d36-35e74e204461)

**Comment by lucianobonzatto** [comment]
Yes, fpv_cam uses libgazebo_ros_camera, but for some reason the topic is not created

**Comment by lucianobonzatto** [comment]
i am trying to spawn a ground robot in the same world, but it is failing. any tips?

Can you tell me where the gazebo world is created since the make px4_sitl gazebo_iris is called? I thought of opening the world with gazebo_ros to be able to make this spawn

**Comment by piradata** [comment]
humm, there is a way.

Give a look [there](https://docs.px4.io/main/en/simulation/ros_interface.html#what-s-happening-behind-the-scenes)

It basically explains what the command `roslaunch mavros px4.launch fcu_url:='udp://:14550@127.0.0.1:14555'` does, so you can use only the part that launches the vehicle that is `rosrun gazebo_ros spawn_model -sdf -file $(pwd)/Tools/simulation/gazebo-classic/sitl_gazebo-classic/models/iris/iris.sdf -model iris -x 0 -y 0 -z 0 -R 0 -P 0 -Y 0`

Anyway, will close this issue as this has nothing more to do with image reading hahah.

But feel free to open another one if you want :)
